services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    container_name: backend_api
    ports:
      - "5000:5000"
    environment:
      - LLAMA_API_KEY=${LLAMA_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_API_KEY=
      - QDRANT_URL=http://qdrant:6333
      - DB_POSTGRES_URL=postgresql://postgres:postgres123@postgres:5432/technical_requirements
      - MINIO_URL=${MINIO_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - ./output:/app/output
      - ./output10:/app/output10
      - ./documents:/app/documents
      - ./data:/app/data
      - ./downloads:/app/downloads
      - ./downloads1:/app/downloads1
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    container_name: frontend_app
    ports:
      - "8080:8080"
    environment:
      - VITE_API_BASE_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    name: technical_requirements_app-network
    external: true